### ISSUE TITLE
Game crashes when no keybind is assigned

### ISSUE THREAD

**Issue by JavidPack** [DeroXP/Nurser-Terraria#1]
The `HealKeyMod.HealKey.GetAssignedKeys()[0]` code is causing the issue, you should first check if the returned list is empty and if it is instead suggest to the user to assign a hotkey.

https://github.com/DeroXP/Nurser-Terraria/blob/e8984d400d6a90db61f3e4f7d11dd5322d218019/Nurser.cs#L88

Issue originally reported in the tModLoader Discord: https://discord.com/channels/103110554649894912/1239713675011424317/1239713675011424317

**Comment by DeroXP** [comment]
Thank you, for telling me. It'll be updated today.
